# 服务配置
server:
  port: 80
# spring配置
spring:
  # 1.应用配置
  application:
    name: dailywork #指定服务名
    # 2.数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:9999/ddwork?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
    url: jdbc:mysql://120.77.209.88:3306/ddwork?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 280617Fk.
    # 3.JPA
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: true
  # security
  security:
    user:
      name: root
      password: 123456
    
    