# 服务配置
server:
  port: 9001
# spring配置
spring:
  # 1.应用配置
  application:
    name: dailywork #指定服务名
    # 2.数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:9999/ihrm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    # 3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
    